### ISSUE TITLE
Cannot call method 'once' of null

### ISSUE THREAD

**Issue by valuks** [josephg/node-browserchannel#48]
v.2.0.0

Sometime nodejs runs in this error. Haven't more details at the moment.
```
TypeError: Cannot call method 'once' of null
    at BCSession._setBackChannel (/project/node_modules/browserchannel/dist/server.js:294:18)
    at processData (/project/node_modules/browserchannel/dist/server.js:657:21)
    at /project/node_modules/browserchannel/dist/server.js:681:20
    at IncomingMessage.<anonymous> (/project/node_modules/browserchannel/dist/server.js:122:12)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by wenzowski** [comment]
...[`res.connection`](https://github.com/josephg/node-browserchannel/blob/master/dist/server.js#L294) is null. Any chance you have an [old version of node](joyent/node#84)?

**Comment by valuks** [comment]
I switched to ingine.io. Maybe later will try with newest node version.
